file_format: "1"
id: charybdis
name: Charybdis
type: shield
url: https://github.com/Bastardkb/Charybdis/
requires: [Nice!Nano]
features:
  - keys
  - pointer
  - underglow
siblings:
  - charybdis_left
  - charybdis_right
